from pathlib import Path


MODEL_PATH = Path("models/face_landmarker.task")

CAMERA_INDEX = 0
PREFERRED_CAMERA_WIDTH = 1280
PREFERRED_CAMERA_HEIGHT = 720

EYE_CLOSED_EAR_THRESHOLD = 0.20
EAR_SMOOTHING_WINDOW = 8
ADAPTIVE_EAR_WINDOW = 300
ADAPTIVE_EAR_MIN_SAMPLES = 60
ADAPTIVE_EAR_PERCENTILE = 0.90
ADAPTIVE_EAR_RATIO = 0.70
ADAPTIVE_EAR_UPDATE_RATE = 0.05
DROWSINESS_SECONDS_THRESHOLD = 2.0
YAWN_MAR_THRESHOLD = 0.60

HEAD_DOWN_PITCH_THRESHOLD = 15.0
HEAD_UP_PITCH_THRESHOLD = -15.0
SIDE_LOOK_YAW_THRESHOLD = 25.0
HEAD_TILT_ROLL_THRESHOLD = 20.0

AUDIO_ALERT_COOLDOWN_SECONDS = 2.0

TELEMETRY_PATH = "data/live_telemetry.json"
TELEMETRY_SAMPLE_SECONDS = 0.50
TELEMETRY_MAX_RECORDS = 600
