from pathlib import Path


MODEL_PATH = Path("models/face_landmarker.task")
ML_MODEL_PATH = Path("models/best_model.joblib")
ML_DROWSY_PROBABILITY_THRESHOLD = 0.50

CAMERA_INDEX = 0
PREFERRED_CAMERA_WIDTH = 1280
PREFERRED_CAMERA_HEIGHT = 720

EYE_CLOSED_EAR_THRESHOLD = 0.20
EYE_CLOSED_CONFIRMATION_RATIO = 0.90
HEAVY_EYE_EAR_RATIO = 1.10
HEAVY_EYE_SECONDS_THRESHOLD = 1.40
EAR_SMOOTHING_WINDOW = 3
ADAPTIVE_EAR_WINDOW = 300
ADAPTIVE_EAR_MIN_SAMPLES = 60
ADAPTIVE_EAR_PERCENTILE = 0.90
ADAPTIVE_EAR_RATIO = 0.70
ADAPTIVE_EAR_UPDATE_RATE = 0.05
DROWSINESS_SECONDS_THRESHOLD = 3.0
NORMAL_BLINK_GRACE_SECONDS = 0.60
NORMAL_BLINK_RISK_CAP = 0.25
SHORT_EYE_CLOSURE_RISK_CAP = 0.45
EYE_CLOSURE_HIGH_RISK_SECONDS = 4.5
EYE_CLOSURE_CRITICAL_SECONDS = 6.0
SLOW_BLINK_SECONDS_THRESHOLD = 0.80
SLOW_BLINK_COUNT_THRESHOLD = 3
MICROSLEEP_SECONDS_THRESHOLD = 4.0
MICROSLEEP_RECENT_SECONDS = 2.0
FREQUENT_BLINKS_PER_MINUTE_THRESHOLD = 25
BLINK_RATE_MIN_OBSERVATION_SECONDS = 20.0
TEMPORAL_SCORING_MIN_SECONDS = 20.0
PERCLOS_WARNING_PERCENT = 25.0
PERCLOS_HIGH_PERCENT = 40.0
YAWN_MAR_THRESHOLD = 0.60
FREQUENT_YAWN_WINDOW_SECONDS = 120
FREQUENT_YAWN_COUNT_THRESHOLD = 3
LONG_YAWN_SECONDS_THRESHOLD = 1.5
YAWN_COUNT_WINDOWS_SECONDS = (60, FREQUENT_YAWN_WINDOW_SECONDS)

HEAD_DOWN_PITCH_THRESHOLD = 22.0
HEAD_UP_PITCH_THRESHOLD = -15.0
SIDE_LOOK_YAW_THRESHOLD = 30.0
HEAD_TILT_ROLL_THRESHOLD = 20.0
PROLONGED_HEAD_DOWN_SECONDS = 4.0
PROLONGED_SIDE_LOOK_SECONDS = 4.0
HEAD_POSE_INSTABILITY_THRESHOLD = 16.0

AUDIO_ALERT_COOLDOWN_SECONDS = 2.0

TELEMETRY_PATH = "data/live_telemetry.json"
TELEMETRY_SAMPLE_SECONDS = 0.50
TELEMETRY_MAX_RECORDS = 600

TEMPORAL_WINDOWS_SECONDS = (10, 30, 60)
TEMPORAL_MIN_SAMPLES = 3
